[package]
name = "hps_decode"
description = "A library for decoding Super Smash Bros. Melee music files"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/DarylPinto/hps_decode"
readme = "README.md"
exclude = ["/test-data"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
rayon = "1.7.0"
thiserror = "1.0.40"
