name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install libasound2-dev
      - name: Cargo check
        run: cargo check --all-features
      - name: Cargo check examples
        run: cargo check --examples --all-features
      - name: Run tests
        run: cargo test --all-features --verbose
